# Generated by Django 3.1.1 on 2020-09-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_wants_to_donate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wants_to_donate',
        ),
    ]
